# Generated by Django 4.0.4 on 2022-10-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0002_alter_user_is_superuser"),
        ("hello", "0002_expectation"),
    ]

    operations = []
