# Generated by Django 4.0.4 on 2022-10-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0003_expectation_current"),
        ("hello", "0003_merge_0002_alter_user_is_superuser_0002_expectation"),
    ]

    operations = []
