# Generated by Django 4.0.4 on 2022-10-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0004_expectation_done"),
        ("hello", "0004_merge_20221025_1508"),
    ]

    operations = []
